services:
  filmhub-server:
    image: filmhub-server:latest
    container_name: filmhub-server
    build:
      context: ./filmhub-server
      dockerfile: Dockerfile
      target: filmhub-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PASSWORD=secret
      - ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
