FROM golang:1.24.2-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o main ./cmd/main.go

FROM alpine:3.17 as filmhub-server

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/.env /app/.env

EXPOSE 8080

ENTRYPOINT ["/app/main"]
